music/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('music_app.urls', namespace='music')),
]

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

music_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'music'

urlpatterns = [
    path('', AlbumView.as_view(), name='album'),
    path('create/album/', AlbumCreateView.as_view(), name='album_create'),
    path('create/song/<slug>/', SongCreateView.as_view(), name='song_create'),
    path('albums/<slug>/', AlbumDetailView.as_view(), name='album_detail'),
    path('<slug>/delete/album/', delete_album, name='delete_album'),
    path('<album_slug>/delete/song/<song_slug>/', delete_song, name='delete_song'),
    path('search/', search, name='search'),
    path('<album_slug>/favourite_album/', favourite_album, name='favourite_album'),
    path('<album_slug>/<song_slug>/favourite_song/', favourite_song, name='favourite_song'),
    path('favourite_songs/', favourite_songs, name='favourite_songs'),
    path('favourite_albums/', favourite_albums, name='favourite_albums'),
]

templates/music/album.html
{% extends 'base.html' %}
{% block title %} {{ title }}{% endblock title %}
{% block body %}
<div class="row row-cols-1 row-cols-md-3 mt-4">
  {% for album in albums %}
  <div class="col-md-3 mb-4">
    <!-- Card -->
    <div class="card mdb grey lighten-4">
      <!--Card image-->
      <div class="view overlay">
        <img class="card-img-top" src="{{ album.album_logo.url }}" alt="Card image cap">
        <a href="{{ album.get_absolute_url }}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <!--Card content-->
      <div class="card-body">
        <!--Title-->
        <h4 class="card-title ml-2">{{ album.album_title }}</h4>
        <!--Text-->
        <p class="ml-2"><span class="h6">Artist: </span>{{ album.artist }}</p>
        <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
        <a href="{{ album.get_absolute_url }}" type="button" class="btn btn-sm mdb unique-color btn-block text-light my-0">
          View Details</a>

      </div>
    </div>
    <!-- Card -->
  </div>

  {% endfor %}

</div>
<div class="row ">
  <div class="col-md-12 ">
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
      <ul class="pagination pg-unique-color justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link " href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link mdb unique-color">{{ i }} <span
              class="sr-only">(current)</span></span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/music/album_create.html
{% extends 'base.html' %}
{% block title %} {{ title }}{% endblock title %}
{% block body %}
<div class="row mt-4">
    <div class="col-lg-7">
        <div class="card card mdb grey lighten-4 p-5 ">
            <h1 class="mb-4">Add a new album</h2>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ field.label }}: {{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                {% if error_message %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ error_message }}</strong>
                </div>
                {% endif %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    {% if field.name == 'private' %}
                    <!-- Default checked -->
                    <!-- <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="id_{{ field.name }}"  >
                        <label class="custom-control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    </div> -->
                    <div>
                        <label for="private" class="mr-1">Private</label>
                    <span >{{ field }}</span>
                    </div>
                    {% else %}
                    <div class="file-upload-wrapper">
                        {% if field.name == 'album_logo' %}
                        <label for="{{ field.name }}">Album logo:</label> <br>
                        {% endif %}
                        <input type="{{ field.field.widget.input_type }}"
                            class="{{ field.field.widget.attrs.class }} mb-3" name="{{ field.name }}"
                            id="id_{{ field.name }}" placeholder="{{ field.field.widget.attrs.placeholder }}">
                    </div>
                    {% endif %}
                    {% endfor %}
                    <!-- {{ form.private }} -->

                    <button class="btn btn-md text-light mdb unique-color btn-block my-4" type="submit">Create</button>
                </form>
        </div>
    </div>
    <div class="col-lg-5">
        <div class="card card mdb grey lighten-4 p-4">
            <h3>What is Music App?</h3>
            <p>Music App is an app that allows you to listen music anywhere anytime by simply uploading and storing all
                your
                music on the cloud.</p>
            <h3>How do I add music?</h3>
            <p>First, create a new album by filling out the form on this page. Once an album is created you will be able
                to add/upload songs.</p>
            <h3>What are some Album logo best practices?</h3>
            <ul>
                <li>Have a resolution of 512x512</li>
                <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                <li>Remain under the 2MB limit.</li>
                <li>Square images look best</li>
            </ul>
        </div>
    </div>
</div>
<script>
    $('.file-upload').file_upload();
</script>
{% endblock %}

templates/music/album_delete.html
{% extends 'base.html' %}

{% block body %}


<div class="row mt-4 justify-content-center">
    <div class="col-md-6">
        <div class="card p-4">
            <form action='.' method='POST'>{% csrf_token %}
                <h4>Do you want to delete the album "{{ album.album_title }}"?</h4>
                <p><a class="btn btn-md btn-info" href='{{ album.get_absolute_url }}'>Cancel</a><input class="btn btn-danger btn-md px-5" type='submit' value='Yes' />  </p>
            </form>
            
        </div>
    </div>
</div>



{% endblock %}

templates/music/album_detail.html
{% extends 'base.html' %}

{% load custom_tags %}


{% block title %} {{ album.album_title }}{% endblock title %}
{% block body %}

<div class="row mt-4">
    <div class="col-lg-4">
        <!-- Card -->
        <div class="card mdb grey lighten-4">
            <!--Card image-->
            <div class="view overlay">
                <img class="card-img-top" src="{{ album.album_logo.url }}" alt="Card image cap">
                <a href="">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card content-->
            <div class="card-body text-center">
                <!--Title-->
                <h4 class="card-title">{{ album.album_title }}</h4>
                <!--Text-->
                <p class="lead"><span class="h6 ">Artist: </span>{{ album.artist }}</p>
                <p class=""><span class="h6 ">Author: </span><a class="myColor" href="{{ album.user.get_absolute_url }}">{{ album.user }}</a></p>
                <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->

                {% if request.user == album.user %}
                <span><a href="{% url 'music:delete_album' album.slug %}" ><i
                            class="far fa-trash-alt border border-dark text-dark p-2 mx-2 mt-md-2"></i></a></i></span>
                {% endif %}
                {% is_favourite_album request.user album as favourite %}
                <span><a href="{% url 'music:favourite_album' album.slug %}"><i
                    class="{% if favourite  %} fas {% else %} far {% endif %} fa-heart border border-dark text-dark p-2 mx- mt-md-2"></i></a></span>
                        
            </div>
        </div>
        <!-- Card -->
    </div>
    <div class="col-lg-8">
        <button class="btn text-light mdb unique-color btn-md mx-2 px-3 ">View All</button>
        {% if request.user == album.user %}
        <a href="{% url 'music:song_create' album.slug %}" class="text-dark px-3 js-create-book">Add New Song</a>
        {% endif %}
        <div class="card p-4 ml-2 mt-2 mdb grey lighten-4">
            <h3>All songs</h3>
            <table class="table">
                {% if album.songs.all %}
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Audio File</th>
                        <th>Favorite</th>

                        {% if request.user == album.user %}
                        <th>Actions</th>
                        {% endif %}

                    </tr>
                </thead>
                {% else %}
                No songs
                {% endif %}
                <tbody>

                    {% for song in album.songs.all %}
                    <td>{{ song.song_title }}</td>
                    <td>
                        <a>
                            <audio onplay="pauseOthers(this);" controls>
                                <source src="{{MUSIC_URL}}{{ song.audio_file.url }}" type="audio/mp3" />
                            </audio>
                        </a>
                    </td>
                    <td>
                        {% is_favourite_song request.user song as favourite %}
                        <span><a href="{% url 'music:favourite_song' album.slug song.slug %}"><i
                            class="{% if favourite  %} fas {% else %} far  {% endif %} fa-heart border border-dark text-dark  p-2 "></i></a></span>
                    </td>

                    {% if request.user == album.user %}
                    <td>
                        <span><a href="{% url 'music:delete_song' album.slug song.slug %} " class="" >
                            <i class="far fa-trash-alt border border-dark text-dark p-2 mx-2"></i></a></i></span>
                    </td>
                    {% endif %}
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    {% endblock %}

templates/music/favourite_albums.html
{% extends 'base.html' %}
{% block title %} Favourite{% endblock title %}

{% block body %}
<h2 class="mt-4 mb-4">Favorite Albums and Songs</span> </h2>
<button class="btn mdb unique-color btn-md text-light ml-0">Albums</button>
<a href="{% url 'music:favourite_songs' %}" class="btn btn-outline-dark btn-md text-light ml-0">SONGS</a>
<div class="row">
    {% for album in albums %}
    
    <div class="col-md-3 mb-4">
        <!-- Card -->
        <div class="card mdb grey lighten-4">
            <!--Card image-->
            <div class="view overlay">
                <img class="card-img-top" src="{{ album.album.album_logo.url }}" alt="Card image cap">
                <a href="{{ album.album.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title ml-2">{{ album.album.album_title }}</h4>
                <!--Text-->
                <p class="ml-2"><span class="h6">Artist: </span>{{ album.album.artist }}</p>

                
            </div>
        </div>
        <!-- Card -->
    </div>
        
    {% empty %}
    <h4 class="ml-3">No favourite albums found</h4>
    {% endfor %}
</div>

{% endblock %}

templates/music/favourite_songs.html
{% extends 'base.html' %}
{% block title %} Favourite{% endblock title %}
{% load custom_tags %}
{% block body %}
<h2 class="mt-4 mb-4">Favorite Albums and Songs</span> </h2>
<a href="{% url 'music:favourite_albums' %}" class="btn btn-outline-dark btn-md text-light ml-0">ALBUMS</a>
<a  href="{% url 'music:favourite_songs' %}"  class="btn mdb unique-color btn-md text-light ml-0">SONGS</a>
<h4 class="mt-4 h4"> Songs</h4>
<div class="row">
    {% if songs %}
    <div class="col-lg-12">
        <div class="card p-4 mdb grey lighten-4">
            <table class="table">
                
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Audio File</th>
                        <th>Favorite</th>
                    </tr>
                </thead>
                <tbody>

                    {% for song in songs %}
                    <tr></tr>
                    <td>{{ song.song.song_title }}</td>
                    <td>
                        <a>
                            <audio onplay="pauseOthers(this);" controls>
                                <source src="{{MUSIC_URL}}{{ song.song.audio_file.url }}" type="audio/mp3" />
                            </audio>
                        </a>
                    </td>
                    <td>
                        {% is_favourite_song request.user song.song as favourite %}
                        <span><a href="{% url 'music:favourite_song' song.song.album.slug song.song.slug %}"><i
                            class="{% if favourite  %} fas {% else %} far  {% endif %} fa-heart border border-dark text-dark  p-2 "></i></a></span>
                    </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h4 class="ml-3">No favourite songs found</h4>
    {% endif %}
</div>

{% endblock %}

templates/music/song_create.html
{% extends 'base.html' %}
{% block title %} {{ title }}{% endblock title %}
{% block body %}
<div class="row mt-4">
    <div class="col-lg-7">
        <div class="card card mdb grey lighten-4 p-5 ">
            <h1 class="mb-4">Add a new Song</h2>
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ field.label }}: {{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}
                {% endif %}

                {% if error_message %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ error_message }}</strong>
                </div>
                {% endif %}

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="file-upload-wrapper">
                        {% if field.name == 'audio_file' %}
                        <label for="{{ field.name }}">Select song:</label> <br>
                        {% endif %}
                        <input type="{{ field.field.widget.input_type }}"
                            class="{{ field.field.widget.attrs.class }} mb-3" name="{{ field.name }}"
                            id="id_{{ field.name }}" placeholder="{{ field.field.widget.attrs.placeholder }}">
                    </div>
                    {% endfor %}

                    <button class="btn btn-md text-light mdb unique-color btn-block my-4" type="submit">Create
                        Song</button>
                </form>
        </div>
    </div>
    <div class="col-lg-5">
        <div class="card card mdb grey lighten-4 p-4">
            <h3>What is Music App?</h3>
            <p>Music App is an app that allows you to listen music anywhere anytime by simply uploading and storing all
                your
                music on the cloud.</p>
            <h3>How do I add music?</h3>
            <p>First, create a new album by filling out the form on this page. Once an album is created you will be able
                to add/upload songs.</p>
            <h3>What are some Album logo best practices?</h3>
            <ul>
                <li>Have a resolution of 512x512</li>
                <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                <li>Remain under the 2MB limit.</li>
                <li>Square images look best</li>
            </ul>
        </div>
    </div>
</div>
<script>
    $('.file-upload').file_upload();
</script>
{% endblock %}

templates/music/song_delete.html
{% extends 'base.html' %}

{% block body %}

<div class="row mt-4 justify-content-center">
    <div class="col-md-6">
        <div class="card p-4">
            <form action='.' method='POST'>{% csrf_token %}
                <h4>Do you want to delete the song "{{ song.song_title }}"?</h4>
                <p> <a class="btn btn-md btn-info" href="{{ album.get_absolute_url }}">Cancel</a><input class="btn btn-danger btn-md px-5" type='submit' value='Yes' /> </p>
            </form>
            
        </div>
    </div>
</div>



{% endblock %}