music/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('music_app.urls', namespace='music')),
]

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

music_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'music'

urlpatterns = [
    path('', AlbumView.as_view(), name='album'),
    path('create/album/', AlbumCreateView.as_view(), name='album_create'),
    path('create/song/<slug>/', SongCreateView.as_view(), name='song_create'),
    path('albums/<slug>/', AlbumDetailView.as_view(), name='album_detail'),
    path('<slug>/delete/album/', delete_album, name='delete_album'),
    path('<album_slug>/delete/song/<song_slug>/', delete_song, name='delete_song'),
    path('search/', search, name='search'),
    path('<album_slug>/favourite_album/', favourite_album, name='favourite_album'),
    path('<album_slug>/<song_slug>/favourite_song/', favourite_song, name='favourite_song'),
    path('favourite_songs/', favourite_songs, name='favourite_songs'),
    path('favourite_albums/', favourite_albums, name='favourite_albums'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/myStyle.css' %}" rel="stylesheet">

    <title>{% block title %}Music{% endblock title %}</title>

</head>

<body style="background-color: #e0e0e0;">
    <div class="">
        <!--Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark unique-color py-0 sticky-top">
            <a class="navbar-brand ml-3" href="/">Music</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
                aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                <ul class="navbar-nav ml-4">
                    <li class="nav-item {{ album_page }}">
                        <a class="nav-link" href="/">
                            <i class="fas fa-record-vinyl"></i> Albums
                        </a>
                    </li>
                    <li class="nav-item {{ songs_page }} ">
                        <a class="nav-link" href="{% url 'music:favourite_albums' %}">
                            <i class="fas fa-music"></i> Favourites 
                        </a>
                    </li>

                        
                    <form class="form-inline my-2 my-lg-0 ml-5" action="{% url 'music:search' %}">
                        <input class="form-control form-control-sm" name="q" type="search" placeholder="Search" aria-label="Search">
                        <!-- <button class="btn btn-white btn-md my-2 my-sm-0 ml-3" type="submit"><span class="text-muted">Search</span></button> -->
                    </form>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item  {{ create_page }}">
                        <a class="nav-link" href="{% url 'music:album_create' %}">
                            <i class="fas fa-plus"></i> Add Album
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item {{ profile_page }}">
                        <a class="nav-link" href="{{ request.user.get_absolute_url }}">
                            <i class="fas fa-user"></i> {{ request.user.username }} </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'account_signup' %}">
                            <i class="fas fa-user-plus"></i> Register
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'account_login' %}">
                            <i class="fas fa-sign-in-alt"></i> Login
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <!--/.Navbar -->

        <!-- Body -->
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {#            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>#}
        {% endfor %}

        {% endif %}
        <div class="container" style="min-height: 490px;">

            {% block body %}

            {% endblock %}
        </div>
        <!-- End body -->

    </div>
    <!--Footer-->
    <footer class="page-footer text-center font-small unique-color mt-4 wow fadeIn py-0">

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2020 Copyright:
            <a href="" target="_blank"> Abdur Rakib </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
    <script src="{% static 'js/album.js' %}"></script>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.12.0/js/mdb.min.js"></script>
</body>

</html>

templates/search_results.html
{% extends 'base.html' %}
{% block title %} Search{% endblock title %}


{% block body %}
<h2 class="mt-4 mb-4">You searched for <span class="font-weight-bold">'{{ query }}'</span> </h2>
<h4 class="h4">Albums</h4>
<div class="row">
    {% for album in albums %}
    <div class="col-md-3 mb-4">
        <!-- Card -->
        <div class="card mdb grey lighten-4">
            <!--Card image-->
            <div class="view overlay">
                <img class="card-img-top" src="{{ album.album_logo.url }}" alt="Card image cap">
                <a href="{{ album.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title ml-2">{{ album.album_title }}</h4>
                <!--Text-->
                <p class="ml-2"><span class="h6">Artist: </span>{{ album.artist }}</p>
                <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->

                
            </div>
        </div>
        <!-- Card -->
    </div>
    {% empty %}
    <h4 class="ml-3">No albums found</h4>
    {% endfor %}
</div>
<h4 class="mt-4 h4"> Songs</h4>
<div class="row">
    {% if songs %}
    <div class="col-lg-12">
        <div class="card p-4 mdb grey lighten-4">
            <table class="table">
                
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Audio File</th>
                        <th>Favorite</th>
                    </tr>
                </thead>
                <tbody>

                    {% for song in songs %}
                    <tr></tr>
                    <td>{{ song.song_title }}</td>
                    <td>
                        <a>
                            <audio onplay="pauseOthers(this);" controls>
                                <source src="{{MUSIC_URL}}{{ song.audio_file.url }}" type="audio/mp3" />
                            </audio>
                        </a>
                    </td>
                    <td>
                        <a href=""><i class="far fa-heart border border-dark text-dark p-2 mx-2"></i></a>
                    </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h4 class="ml-3">No songs found</h4>
    {% endif %}
</div>
{% endblock %}